-- DK Bot v2 — 메뉴 공용 지식 문서 + 증분 색인 작업 큐.
-- 기존 wbs_embeddings / minute_embeddings 는 전환 검증이 끝날 때까지 유지한다.
-- 문서 안정 키에는 project scope를 포함하고 content_hash는 넣지 않는다.
-- 내용 변경은 같은 프로젝트/엔티티/청크 행을 갱신한다.

-- Supabase may install extensions in either public or extensions. Keep every
-- unqualified vector type/operator reference portable across both layouts.
set search_path = public, extensions;

create extension if not exists vector;

create table if not exists public.ai_documents (
  id                   uuid primary key default gen_random_uuid(),
  project_id           uuid references public.projects(id) on delete cascade,
  project_scope        text generated always as (coalesce(project_id::text, 'global')) stored,
  domain               text not null,
  entity_type          text not null,
  entity_id            text not null,
  chunk_no             integer not null check (chunk_no >= 0),
  index_version        integer not null default 1 check (index_version > 0),
  title                text not null default '',
  content              text not null,
  content_hash         text not null,
  href                 text not null,
  team                 text,
  occurred_on          date,
  source_updated_at    timestamptz,
  embedding_model      text not null,
  embedding_dimensions integer not null default 768 check (embedding_dimensions = 768),
  chunker_version      text not null,
  embedding            vector(768),
  indexed_at           timestamptz not null default now(),
  constraint ai_documents_stable_key unique
    (project_scope, domain, entity_type, entity_id, chunk_no, index_version)
);

-- An early development copy of 0031 used a project-agnostic key. Keep reruns safe
-- before any worker/backfill is connected.
alter table public.ai_documents
  add column if not exists project_scope text
  generated always as (coalesce(project_id::text, 'global')) stored;
alter table public.ai_documents
  drop constraint if exists ai_documents_domain_entity_type_entity_id_chunk_no_index_version_key;
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.ai_documents'::regclass
      and conname = 'ai_documents_stable_key'
  ) then
    alter table public.ai_documents
      add constraint ai_documents_stable_key unique
      (project_scope, domain, entity_type, entity_id, chunk_no, index_version);
  end if;
end $$;

create index if not exists ai_documents_project_domain_idx
  on public.ai_documents (project_id, domain, entity_type);
create index if not exists ai_documents_entity_idx
  on public.ai_documents (domain, entity_type, entity_id, index_version);
create index if not exists ai_documents_occurred_idx
  on public.ai_documents (occurred_on desc) where occurred_on is not null;
create index if not exists ai_documents_vector_idx
  on public.ai_documents using hnsw (embedding vector_cosine_ops);

alter table public.ai_documents enable row level security;
-- [RLS 계약] (리뷰 L-3) 현행 원본 테이블들(minutes/announcements/weekly 등)의 읽기 정책이
-- 전부 authenticated using (true)라서, 색인 사본인 이 테이블도 동일 정책을 유지해도
-- 노출 순증이 없다 — 그래서 의도적으로 같은 정책을 쓴다.
-- 단, 향후 프로젝트 ACL(예: app_role() 헬퍼 + 프로젝트 멤버십 검사)을 원본에 도입하면
-- 이 정책도 원본과 반드시 함께 갱신해야 하며, 백필(재색인) 전에 정책 정렬을 끝내는 것이
-- 게이트다. 정렬 없이 백필하면 색인 사본이 원본보다 넓게 노출된다.
-- (프로덕션 RLS 헬퍼는 app_role()이다. current_role()은 레포 드리프트이므로 참조 금지.)
drop policy if exists ai_documents_read on public.ai_documents;
create policy ai_documents_read on public.ai_documents
  for select to authenticated using (true);
revoke all on table public.ai_documents from public, anon, authenticated;
grant select on table public.ai_documents to authenticated;
grant all on table public.ai_documents to service_role;

-- service role 전용 큐. 같은 엔티티의 새 변경은 기존 행을 pending으로 되돌려 중복 폭증을 막는다.
create table if not exists public.ai_index_jobs (
  id             bigint generated by default as identity primary key,
  job_key        text not null unique,
  operation      text not null check (operation in ('upsert', 'delete')),
  project_id     uuid references public.projects(id) on delete cascade,
  domain         text not null,
  entity_type    text not null,
  entity_id      text not null,
  payload        jsonb not null default '{}'::jsonb,
  status         text not null default 'pending'
                   check (status in ('pending', 'running', 'done', 'dead_letter')),
  attempts       integer not null default 0 check (attempts >= 0),
  run_after      timestamptz not null default now(),
  locked_at      timestamptz,
  last_error     text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists ai_index_jobs_claim_idx
  on public.ai_index_jobs (status, run_after, id);

alter table public.ai_index_jobs enable row level security;
-- 일반 사용자의 직접 읽기/쓰기는 허용하지 않는다. service role만 RLS를 우회한다.
revoke all on table public.ai_index_jobs from public, anon, authenticated;
grant all on table public.ai_index_jobs to service_role;
do $$
declare
  v_sequence text;
begin
  v_sequence := pg_get_serial_sequence('public.ai_index_jobs', 'id');
  if v_sequence is not null then
    execute format(
      'revoke all on sequence %s from public, anon, authenticated',
      v_sequence::regclass
    );
    execute format('grant usage, select on sequence %s to service_role', v_sequence::regclass);
  end if;
end $$;

-- One entity/version re-chunk is one transaction. The advisory lock serializes
-- competing workers and indexed/source timestamps prevent a delayed older job
-- from deleting chunks written by a newer job.
create or replace function public.replace_ai_document_chunks(
  p_project_id uuid,
  p_domain text,
  p_entity_type text,
  p_entity_id text,
  p_index_version integer,
  p_source_updated_at timestamptz,
  p_indexed_at timestamptz,
  p_documents jsonb
) returns integer
language plpgsql volatile security invoker
set search_path = public, extensions
as $$
declare
  v_count integer;
  v_distinct_count integer;
  v_min_chunk integer;
  v_max_chunk integer;
  v_existing_source timestamptz;
  v_existing_indexed timestamptz;
begin
  if jsonb_typeof(p_documents) <> 'array' or jsonb_array_length(p_documents) = 0 then
    raise exception 'AI_DOCUMENT_CHUNKS_INVALID' using errcode = '22023';
  end if;

  select count(*), count(distinct x.chunk_no), min(x.chunk_no), max(x.chunk_no)
    into v_count, v_distinct_count, v_min_chunk, v_max_chunk
  from jsonb_to_recordset(p_documents) as x(chunk_no integer);
  if v_count <> v_distinct_count or v_min_chunk <> 0 or v_max_chunk <> v_count - 1 then
    raise exception 'AI_DOCUMENT_CHUNKS_NON_CONTIGUOUS' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    coalesce(p_project_id::text, 'global') || '|' || p_domain || '|' ||
    p_entity_type || '|' || p_entity_id || '|' || p_index_version::text,
    0
  ));

  select max(source_updated_at), max(indexed_at)
    into v_existing_source, v_existing_indexed
  from public.ai_documents
  where project_id is not distinct from p_project_id
    and domain = p_domain
    and entity_type = p_entity_type
    and entity_id = p_entity_id
    and index_version = p_index_version;

  if v_existing_source is not null and (
    p_source_updated_at is null
    or v_existing_source > p_source_updated_at
    or (v_existing_source = p_source_updated_at and v_existing_indexed > p_indexed_at)
  ) then
    return 0;
  end if;
  if v_existing_source is null and v_existing_indexed > p_indexed_at then
    return 0;
  end if;

  insert into public.ai_documents (
    project_id, domain, entity_type, entity_id, chunk_no, index_version,
    title, content, content_hash, href, team, occurred_on, source_updated_at,
    embedding_model, embedding_dimensions, chunker_version, embedding, indexed_at
  )
  select
    p_project_id, p_domain, p_entity_type, p_entity_id, x.chunk_no, p_index_version,
    x.title, x.content, x.content_hash, x.href, x.team, x.occurred_on,
    p_source_updated_at, x.embedding_model, x.embedding_dimensions,
    x.chunker_version,
    case when x.embedding is null or x.embedding = 'null'::jsonb
      then null else (x.embedding::text)::vector(768) end,
    p_indexed_at
  from jsonb_to_recordset(p_documents) as x(
    chunk_no integer,
    title text,
    content text,
    content_hash text,
    href text,
    team text,
    occurred_on date,
    source_updated_at timestamptz,
    embedding_model text,
    embedding_dimensions integer,
    chunker_version text,
    embedding jsonb
  )
  on conflict (project_scope, domain, entity_type, entity_id, chunk_no, index_version)
  do update set
    project_id = excluded.project_id,
    title = excluded.title,
    content = excluded.content,
    content_hash = excluded.content_hash,
    href = excluded.href,
    team = excluded.team,
    occurred_on = excluded.occurred_on,
    source_updated_at = excluded.source_updated_at,
    embedding_model = excluded.embedding_model,
    embedding_dimensions = excluded.embedding_dimensions,
    chunker_version = excluded.chunker_version,
    embedding = excluded.embedding,
    indexed_at = excluded.indexed_at;

  delete from public.ai_documents
  where project_id is not distinct from p_project_id
    and domain = p_domain
    and entity_type = p_entity_type
    and entity_id = p_entity_id
    and index_version = p_index_version
    and chunk_no >= v_count;

  return v_count;
end;
$$;

-- Re-chunking mutates the index and is intentionally unavailable to browser roles.
revoke all on function public.replace_ai_document_chunks(
  uuid, text, text, text, integer, timestamptz, timestamptz, jsonb
) from public, anon, authenticated;
grant execute on function public.replace_ai_document_chunks(
  uuid, text, text, text, integer, timestamptz, timestamptz, jsonb
) to service_role;

-- 반환 컬럼은 어댑터 mapDocument가 요구하는 문서 필드 전체와 일치해야 한다(리뷰 M-9).
-- 벡터 검색이 이 RPC 단일 호출로 완성되므로 2차 하이드레이트 재조회가 없다.
-- 반환 타입 변경은 create or replace로 불가하므로 이전 개발 사본이 남은 DB를 위해 먼저 drop한다.
drop function if exists public.match_ai_documents(
  vector, int, uuid[], boolean, text[], text[], text, date, date, int
);
create function public.match_ai_documents(
  query_embedding vector(768),
  match_count int default 20,
  p_project_ids uuid[] default null,
  p_include_global boolean default false,
  p_domains text[] default null,
  p_entity_types text[] default null,
  p_team text default null,
  p_date_from date default null,
  p_date_to date default null,
  p_index_version int default 1
) returns table (
  id uuid,
  project_id uuid,
  domain text,
  entity_type text,
  entity_id text,
  chunk_no integer,
  index_version integer,
  title text,
  content text,
  content_hash text,
  href text,
  team text,
  occurred_on date,
  source_updated_at timestamptz,
  embedding_model text,
  embedding_dimensions integer,
  chunker_version text,
  indexed_at timestamptz,
  similarity float
)
language sql stable security invoker
set search_path = public, extensions
as $$
  select
    d.id, d.project_id, d.domain, d.entity_type, d.entity_id, d.chunk_no,
    d.index_version, d.title, d.content, d.content_hash, d.href, d.team,
    d.occurred_on, d.source_updated_at, d.embedding_model, d.embedding_dimensions,
    d.chunker_version, d.indexed_at,
    1 - (d.embedding <=> query_embedding) as similarity
  from public.ai_documents d
  where d.embedding is not null
    and d.index_version = p_index_version
    -- NULL/empty project scopes never mean "all projects". Global rows require
    -- their own explicit flag and remain independent of the project list.
    and (
      (p_project_ids is not null and d.project_id = any(p_project_ids))
      or (p_include_global and d.project_id is null)
    )
    and (p_domains is null or d.domain = any(p_domains))
    and (p_entity_types is null or d.entity_type = any(p_entity_types))
    and (p_team is null or d.team = p_team)
    and (p_date_from is null or d.occurred_on >= p_date_from)
    and (p_date_to is null or d.occurred_on <= p_date_to)
  order by d.embedding <=> query_embedding
  -- Explicit NULL from an RPC caller must not turn into PostgreSQL's
  -- unbounded `LIMIT NULL`; keep every retrieval bounded server-side.
  limit greatest(1, least(coalesce(match_count, 20), 100));
$$;

revoke all on function public.match_ai_documents(
  vector, int, uuid[], boolean, text[], text[], text, date, date, int
) from public, anon;
grant execute on function public.match_ai_documents(
  vector, int, uuid[], boolean, text[], text[], text, date, date, int
) to authenticated, service_role;

reset search_path;
