-- 서버 LLM 설정 — LLM 접속 프로필(llm_profiles) + 전역 활성 설정 싱글톤(llm_config).
--
-- 배경: 지금까지 LLM 접속 정보는 배포 env(AI_PROVIDER / GEMINI_API_KEY / LLM_BASE_URL 등)에만
-- 존재해 모델·엔드포인트를 바꾸려면 재배포가 필요했다. 관리 화면(/admin/llm-config)에서
-- 프로필을 여러 개 등록해 두고 그중 하나를 서버 전역 LLM으로 즉시 전환할 수 있게 한다.
--   · llm_profiles : 이름 붙은 접속 정보 한 벌(provider/base_url/model/auth_token/토큰 한도).
--                    preset_id 는 폼 프리셋(gemini/openai/ollama/lmstudio/custom) 출처 기록용 —
--                    provider 는 앱의 AiProvider 2종만 허용하고, OpenAI 호환 서버는 openai+base_url 로 커버한다.
--   · llm_config   : id=1 고정 싱글톤. mode='env'(기존 env 그대로·기본값) / 'profile'(활성 프로필)
--                    / 'none'(LLM 기능 차단). mode<>'profile' 이면 active_profile_id 는 null 로 둔다.
--
-- 범위(임베딩 제외): EMBED_* env 로 동작하는 임베딩 설정은 이번 범위가 아니다 —
-- 이 테이블들은 텍스트 생성 LLM(llmConfig()/hasLLM()) 경로만 오버라이드한다.
--
-- 보안: auth_token 은 평문 저장이고, 보호는 전적으로 RLS(pmo_admin 전용, select 포함)에 의존한다.
--       내부 도구 전제의 의도적 선택이다 — 런타임 소비는 service_role 캐시 로더(lib/ai/llm-override.ts)가
--       RLS 우회로 읽으므로 일반 사용자에게 select 를 열 이유가 없다. 정책을 넓히면 그 즉시
--       토큰이 브라우저로 노출된다. 강화가 필요해지면 Supabase Vault 로 후속 전환할 것.
--       ※ 여기서 revoke all from authenticated 로 더 조이지는 않는다 — 테이블 GRANT 가 없으면
--         RLS 정책이 있어도 관리자 화면 자체가 동작하지 않기 때문(방어선은 정책 조건식).
--
-- 활성 프로필 삭제: FK on delete set null 로 참조를 자동 해제한다(dangling 방지).
--       그 결과 mode='profile' 인데 active_profile_id 가 null 인 상태가 생길 수 있고,
--       이는 로더에서 env 모드로 해석한다(앱 계약 — 스펙 §5).
--
-- 멱등: SQL Editor 반복 실행 안전(create table if not exists / on conflict do nothing /
--       drop policy if exists 선행).
-- 적용: Supabase Management API — POST /v1/projects/<ref>/database/query (0030/0034 와 동일 경로).
--       .env.local 의 SUPABASE_DB_URL 은 비어 있으므로 pg 직결/db push 는 사용하지 않는다.
-- 적용 순서: 이 마이그레이션을 **먼저** 적용한 뒤 코드를 배포한다(0027 PGRST 사고 교훈) —
--       테이블이 없는 상태로 로더가 돌면 매 요청 PGRST 오류가 로그를 오염시킨다.
-- 롤백: 0038_llm_config_rollback.sql (저장된 프로필/설정 소실 — 롤백 파일 헤더 경고 참조).
-- 주의: RLS 헬퍼는 public.app_role() (0012/0013 에서 생성, memberships.role 조회). 재정의하지 말 것.

-- ── 1) LLM 접속 프로필 ──
-- id 는 0031(ai_index_jobs) 관례대로 identity bigint. 이름은 단일 풀이라 단순 unique
-- (중복 시 23505 → 앱이 '이미 같은 이름의 프로필이 있습니다' 로 번역).
-- updated_at 트리거 없음 — 레포 관례(0023/0030)대로 앱이 직접 갱신한다.
create table if not exists llm_profiles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  preset_id text not null,                                  -- 폼 프리셋 출처(gemini/openai/ollama/lmstudio/custom)
  provider text not null check (provider in ('gemini', 'openai')),
  base_url text,                                            -- 빈값 = provider 기본 엔드포인트(해석은 앱 로더)
  model text not null,
  auth_token text,                                          -- 평문 — 위 보안 주석 참조. 응답에는 마스킹만 노출
  max_input_tokens int,
  max_output_tokens int,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ── 2) 전역 활성 설정(싱글톤) ──
-- id = 1 체크로 행이 둘 이상 생기는 것을 DB 레벨에서 막는다(앱은 항상 id=1 을 upsert/update).
create table if not exists llm_config (
  id int primary key default 1 check (id = 1),
  mode text not null default 'env' check (mode in ('env', 'profile', 'none')),
  active_profile_id bigint references llm_profiles(id) on delete set null,
  -- 계정 삭제가 설정 행을 잠그지 않도록 감사 컬럼도 set null (감사값 소실 < 삭제 실패).
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

-- 싱글톤 행 보장. 재적용 시 기존 설정을 덮지 않도록 do nothing.
insert into llm_config (id) values (1) on conflict do nothing;

-- ── 3) RLS (enable 이 전제 — 누락 시 기본 GRANT 로 authenticated 읽기/쓰기가 그대로 열린다) ──
alter table llm_profiles enable row level security;
alter table llm_config enable row level security;

-- 두 테이블 모두 pmo_admin 전용(auth_token 이 있으므로 읽기도 잠근다).
-- 런타임 소비는 service_role 캐시 로더가 담당하므로 일반 사용자 select 는 필요 없다.
drop policy if exists admin_all_llm_profiles on llm_profiles;
create policy admin_all_llm_profiles on llm_profiles for all to authenticated
  using (app_role() = 'pmo_admin') with check (app_role() = 'pmo_admin');

drop policy if exists admin_all_llm_config on llm_config;
create policy admin_all_llm_config on llm_config for all to authenticated
  using (app_role() = 'pmo_admin') with check (app_role() = 'pmo_admin');
