-- 이슈관리 (프로젝트 스코프) — 리스크/장애물 트래킹. 스펙: docs/superpowers/specs/2026-07-23-issues-mvp-design.md §2.
-- 권한: 읽기 = 인증 사용자 전체(0013 회의 관례) / 생성 = 멤버십 보유자 본인 /
--       수정 = 멤버 전체 백스톱 — 행 단위 RLS 로는 열 단위 요구(상태·담당자·조치메모는 멤버 전체,
--       제목·내용·심각도·기한은 작성자/pmo_admin)를 표현할 수 없어 의도적으로 완화한다.
--       세분화는 서버 액션(src/app/actions/issues.ts)이 fail-closed 로 강제 / 삭제 = 작성자 또는 pmo_admin.
-- 멱등: SQL Editor 반복 실행 안전(create table if not exists / create index if not exists /
--       drop policy if exists 선행).
-- 적용: Supabase Management API — POST /v1/projects/<ref>/database/query (0030/0034/0038 과 동일 경로).
--       .env.local 의 SUPABASE_DB_URL 은 비어 있으므로 pg 직결/db push 는 사용하지 않는다.
-- 적용 순서: 이 마이그레이션을 **먼저** 적용한 뒤 코드를 배포한다(0027 PGRST 사고 교훈) —
--       테이블이 없는 상태로 getIssues 가 돌면 매 요청 PGRST 오류가 로그를 오염시킨다.
-- 롤백: 0041_issues_rollback.sql (등록된 이슈 전량 + issue_no 발번 이력 소실 — 롤백 파일 헤더 경고 참조).
-- 주의: RLS 헬퍼는 public.app_role() (0012/0013 에서 생성, memberships.role 조회). 재정의하지 말 것.
--       updated_at 트리거 없음 — 레포 관례(0023/0030/0038)대로 앱이 직접 갱신한다
--       (AI 인덱스 신선도 가드의 입력이므로 쓰기 액션마다 갱신 필수).

-- ── 1) 복합 FK 전제: project_members(id, project_id) 유니크 인덱스 ──
-- 0032 에서 이미 생성됨(프로덕션 적용 확인) — 신규/미적용 DB 재현을 위해 같은 이름으로
-- 방어적 재선언(멱등 no-op). 이 인덱스가 없으면 아래 복합 FK 생성이 실패한다.
create unique index if not exists project_members_id_project_uidx
  on public.project_members (id, project_id);

-- ── 2) 이슈 테이블 ──
-- issue_no 는 0031(ai_index_jobs)/0038(llm_profiles) 관례의 identity bigint — 표시 "#12".
-- 시퀀스 발번이라 동시 등록에도 중복이 없다. 소급 발번 불가 → day-one 필수(스펙 §2).
create table if not exists issues (
  id uuid primary key default gen_random_uuid(),
  issue_no bigint generated by default as identity unique,
  project_id uuid not null references projects(id) on delete cascade,
  title text not null,
  body text not null default '',
  status text not null default 'open'
    check (status in ('open','in_progress','resolved','on_hold')),
  severity text not null default 'medium'
    check (severity in ('high','medium','low')),
  assignee_member_id uuid,
  due_date date,
  resolution_note text not null default '',
  resolved_at timestamptz,                                     -- resolved 진입 시각. 소급 복원 불가 → day-one
  created_by uuid references auth.users(id) on delete set null,
  created_by_name text,                                        -- 탈퇴 후 표시용 스냅샷 (0013 회의 관례)
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),               -- AI 인덱스 신선도 가드의 필수 입력 (0031/0033 접점 전제)
  -- 타 프로젝트 멤버 담당 혼입 DB 차단 (0032 근태 선례의 유니크 인덱스 재사용).
  -- 주의: 컬럼 지정 SET NULL 구문 필수 — 무지정 SET NULL 은 NOT NULL project_id 까지
  -- null 시도되어 멤버 삭제가 런타임 실패한다. 프로덕션 PG 17.6 실측으로 구문 사용 가능 확인.
  constraint issues_assignee_project_fk
    foreign key (assignee_member_id, project_id)
    references project_members (id, project_id)
    on delete set null (assignee_member_id)
);

create index if not exists issues_project_idx on issues(project_id, created_at desc);

-- ── 3) RLS (enable 이 전제 — 누락 시 기본 GRANT 로 authenticated 읽기/쓰기가 그대로 열린다) ──
alter table issues enable row level security;

-- 읽기 전체 (앱 관례 — 0013 과 동일)
drop policy if exists read_all_issues on issues;
create policy read_all_issues on issues for select to authenticated using (true);

-- 생성: 본인 + 멤버십 보유자 (0013 과 동일)
drop policy if exists insert_own_issues on issues;
create policy insert_own_issues on issues
  for insert to authenticated
  with check (created_by = auth.uid() and app_role() is not null);

-- 수정: 멤버 전체 백스톱 — 0013 의 작성자 한정과 다른 의도적 완화(헤더 주석 참조).
-- 진행 필드(상태·담당자·조치메모) vs 전체 편집의 세분화는 서버 액션이 담당한다.
drop policy if exists member_update_issues on issues;
create policy member_update_issues on issues
  for update to authenticated
  using (app_role() is not null)
  with check (app_role() is not null);

-- 삭제: 작성자 또는 pmo_admin (0013 과 동일)
drop policy if exists delete_own_issues on issues;
create policy delete_own_issues on issues
  for delete to authenticated
  using (created_by = auth.uid() or app_role() = 'pmo_admin');
